name: Draft Release
description: Draft a release PR/branch.

outputs:
  version:
    description: "Version that was prepared for release"
  release_branch:
    description: "Release branch name"
  pr_number:
    description: "Created release PR number"
  pr_url:
    description: "Created release PR URL"

runs:
  using: "node20"
  main: "dist/index.js"
