name: 'Create a Release'
description: 'Create a release for a tag in your repository'
author: 'GitHub'
inputs:
  body:
    description: 'Text describing the contents of the tag.'
    required: false

outputs:
  id:
    description: 'The ID of the created Release'
  upload_url:
    description: 'The URL for uploading assets to the release'

runs:
  using: 'node12'
  main: 'dist/index.js'